"""Report generation for GitHub analytics data."""

from datetime import datetime, timezone

from .analyzer import ProfileAnalysis


class Reporter:
    def generate_markdown(self, analysis: ProfileAnalysis) -> str:
        lines = []

        lines.append(f"# GitHub Profile Analysis: {analysis.profile.username}")
        lines.append("")
        now = datetime.now(timezone.utc)
        lines.append(f"*Generated on {now.strftime('%Y-%m-%d %H:%M:%S')}*")
        lines.append("")

        lines.append("## Profile Information")
        lines.append("")
        lines.append("| Field | Value |")
        lines.append("|-------|-------|")
        lines.append(f"| Name | {analysis.profile.name or 'Not specified'} |")
        lines.append(f"| Bio | {analysis.profile.bio or 'Not specified'} |")
        lines.append(f"| Location | {analysis.profile.location or 'Not specified'} |")
        lines.append(f"| Company | {analysis.profile.company or 'Not specified'} |")
        lines.append(f"| Public Repos | {analysis.profile.public_repos} |")
        lines.append(f"| Followers | {analysis.profile.followers} |")
        lines.append(f"| Following | {analysis.profile.following} |")
        lines.append("")

        lines.append("## Repository Statistics")
        lines.append("")
        lines.append("| Metric | Value |")
        lines.append("|--------|-------|")
        lines.append(f"| Total Repos | {len(analysis.repos)} |")
        lines.append(f"| Total Stars | {analysis.total_stars} |")
        lines.append(f"| Total Forks | {analysis.total_forks} |")
        lines.append("")

        if analysis.languages:
            lines.append("## Language Distribution")
            lines.append("")
            lines.append("| Language | Repos | Percentage |")
            lines.append("|----------|-------|------------|")
            total = sum(analysis.languages.values())
            for lang, count in analysis.languages.items():
                percentage = (count / total) * 100
                lines.append(f"| {lang} | {count} | {percentage:.1f}% |")
            lines.append("")

        lines.append("## Scores")
        lines.append("")
        lines.append("| Score | Value |")
        lines.append("|-------|-------|")
        lines.append(f"| Activity Score | {analysis.activity_score}/100 |")
        lines.append(f"| Profile Completeness | {analysis.completeness_score}/100 |")
        lines.append("")

        if analysis.recommendations:
            lines.append("## Recommendations")
            lines.append("")
            for i, rec in enumerate(analysis.recommendations, 1):
                lines.append(f"{i}. {rec}")
            lines.append("")

        lines.append("## Repositories")
        lines.append("")
        lines.append("| Name | Description | Language | Stars | Forks |")
        lines.append("|------|-------------|----------|-------|-------|")
        for repo in analysis.repos:
            desc = (repo.description or "No description")[:50]
            if len(repo.description or "") > 50:
                desc += "..."
            lang = repo.language or 'N/A'
            lines.append(
                f"| {repo.name} | {desc} | {lang} | {repo.stars} | {repo.forks} |"
            )
        lines.append("")

        lines.append("---")
        lines.append("")
        lines.append("*Generated by [GitHub Analytics CLI](https://github.com/EminSans1/github-analytics)*")

        return "\n".join(lines)
